### ISSUE TITLE
USB joysticks (like THEC64 joystick): should it work with vc64web on iPad?

### ISSUE THREAD

**Issue by ChristianWeyer** [vc64web/virtualc64web#168]
Hey all,

my THEC64 joystick works fine with the Apple USB Adapter and my MBP when playing via vc64web.

The same does not work on my iPad - should it work @mithrendal ?
Thanks!

**Comment by ChristianWeyer** [comment]
I think it should:
https://caniuse.com/?search=Gamepad%20Api

But on https://gamepad-tester.com/ it does not show when pressing a button.

**Comment by mithrendal** [comment]
for iOS/iPadOS you have to pair controller in the iOS bluetooth settings I guess... only BT joysticks work which are MFI (made for iPhone) or XBoxWireless Controller or playstation controller ...

you have to google for which controller can I use on my iPad/iPhone ... when you are able to pair the controller and you see it in the iPads bluetooth settings then you can select it in vAmigaWeb

**Comment by ChristianWeyer** [comment]
Thanks!

**Comment by mithrendal** [comment]
hope you have installed vc64web on your homescreen, as doing this and starting from home screen instead of safari... it will remove annoying safari adress/ menu bars and also the annoying safari swipe gestures ... 😎  in general PWAs (progressive web apps ) will behave nearly like native apps when installed to home screen
