### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by fieserWolF** [vc64web/virtualc64web#183]
my OS: Linux 6.1.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.4-1 (2023-01-07) x86_64 GNU/Linux

1. There are outdated compiling instructions here:
https://github.com/vc64web/virtualc64web/wiki/summary

These instructions do not fit to the Makefile any more.
Should be (solution):
- make
- make bin
- make publish

2. Might just be my system, but I had to set "FROZEN_CACHE = False" in /usr/share/emscripten/.emscripten

3. Compile error, might be an error in emscripten itself:
 File "/usr/lib/python3.10/subprocess.py", line 1780, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by mithrendal** [comment]
>make bin

@fieserWolF thank you... I corrected the docs...

normally I compile on MacOS... in order to reproduce your problem I just cloned the virtualc64web repo on a linux system...

` Linux mymachine 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`
then with `make` `make bin` and `./start.sh` I compiles without any warning and starts the local web server where I can run the emulated c64 with chrome ...

lets check the other environment stuff:
here are mine...
`emsdk list` outputs this
 3.1.27    INSTALLED
 node-14.18.2-64bit       	INSTALLED

`make --version` outputs
GNU Make 4.3


`.emscripten`
import os
emsdk_path = os.path.dirname(os.getenv('EM_CONFIG')).replace('\\', '/')
NODE_JS = emsdk_path + '/node/14.18.2_64bit/bin/node'
LLVM_ROOT = emsdk_path + '/upstream/bin'
BINARYEN_ROOT = emsdk_path + '/upstream'
EMSCRIPTEN_ROOT = emsdk_path + '/upstream/emscripten'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]



>3.Compile error, might be an error in emscripten itself:

this error looks like that it has difficulties to do the following line (my bet) as it wants to exec a shell command hence it speaks of subprocess.fork_exec but it cannot find  CURDIR???
`CPPFLAGS   = -I $(CURDIR) $(addprefix -I, $(shell find $(CURDIR) -type d))`

or maybe this ?
`@for dir in $(SUBDIRS); do \`

I bet most likely the error comes from an incompatible installed toolchain e.g. `emsdk` `make` or `node` ... maybe you want to check the installed versions of yours ... when it is for some help of you I can also check the versions of these tools on my main MacOS system... just tell me

(for my other project https://github.com/vAmigaWeb/vAmigaWeb we exchanged `make` to the more platform agnostic `CMake`  which at least does circumvent many of these platform specific environment problems ... eventually we should give vc64web some CMake love soon... as @dirkwhoffmann recently implemented the Commodore REU that together with CMake would be great for GEOs lovers and builders 8-) 

good luck !

**Comment by fieserWolF** [comment]
Thanks so much for your very detailed help!
Point is: Stupid me installed the debian "emscripten" package instead of downloading the emsdk like you recommended in your instructions. After following your instruction, the "make"-process worked well.
I really appreciate your work, really cool stuff!

**Comment by mithrendal** [comment]
you are welcome ❤️
